services:
  gunicorn:
    build: .
      #context: .
      #dockerfile: ./Dockerfile
    container_name: gunicorn
    #command: gunicorn restaurant_purchases.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    ports: 
      - "8000:8000"
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - pgdb
      - redis
  
  nginx:
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
      - flower
  
  pgdb:
    image: postgres:14.3
    hostname: pgdb
    restart: always
    env_file:
     - .pgdb_env
    #environment:
    #  - DATABASE_URL=pgsql://postgres:1234567890@mydb:5432
    #  - POSTGRES_DB=mydb
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
  postgresql_client:
    image: postgresql14-client
    depends_on:
      - pgdb
  
  redis:
    image: redis:6
  
  flower:
    image: mher/flower:0.9.5
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    environment:
    - FLOWER_BASIC_AUTH=admin:admin
    expose:  # new
      - 5555
    depends_on:
      - redis

volumes:
  pgbdata: null
