services:
  gunicorn:
    build: .
    container_name: gunicorn
    command: gunicorn restaurant_purchases.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
    ports: 
      - "8000:8000"
    depends_on: 
      - pgdb
  
  pgdb:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
volumes:
  pgbdata: null