services:
  gunicorn:
    build: .
    container_name: gunicorn
    #command: gunicorn restaurant_purchases.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
    ports: 
      - "8000:8000"
    depends_on: 
      - pgdb
  
  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/app/static
    ports:
      - "80:80"
    depends_on:
      - gunicorn
  
  pgdb:
    image: postgres:14.3-alpine
    hostname: pgdb
    restart: always
    #environment:
    #  - DATABASE_URL=pgsql://postgres:1234567890@mydb:5432
    #  - POSTGRES_DB=mydb
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
volumes:
  pgbdata: null
  static: null