services:
  gunicorn:
    build: .
    container_name: gunicorn
    #command: gunicorn restaurant_purchases.wsgi:application --bind 68.183.201.244:8000
    volumes: 
      - static:/static
    ports: 
      - "8000:8000"
    depends_on: 
      - pgdb
    
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - gunicorn
  
  pgdb:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
volumes:
  pgbdata: null
  static: null