services:
  django:
    build: .
    container_name: django
    command: gunicorn restaurant_purchases.wsgi:application --bind 134.122.43.197:8000 --daemon
    volumes: 
      - .:./
    ports: 
      - "8000:8000"
    depends_on: 
      - pgdb
  
  pgdb:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
volumes:
  pgbdata: null