services:
  gunicorn:
    build: .
    container_name: gunicorn
    #command: gunicorn restaurant_purchases.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    ports: 
      - "8000:8000"
      - "5000:5000"
    depends_on: 
      - pgdb
      - redis
  
  nginx:
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
  
  pgdb:
    image: postgres:14.3
    hostname: pgdb
    restart: always
    environment:
      - DATABASE_URL=pgsql://postgres:1234567890@mydb:5432
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    container_name: pgdb
    volumes: 
      - pgbdata:/var/lib/postgresql/data/
  
  redis:
    image: redis:6

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - pgdb

volumes:
  pgbdata: null
