# Generated by Django 4.0.4 on 2022-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_reciperequirement_ingridient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
