# Generated by Django 4.0.4 on 2022-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='temporary_field',
            field=models.FloatField(default=0.0),
        ),
    ]
