# Generated by Django 4.0.4 on 2022-06-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_telegramnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotification',
            name='status',
            field=models.CharField(choices=[('FreeTask', 'free_task'), ('BusyTask', 'busy_task'), ('ProcessTask', 'process_task')], default='FreeTask', max_length=32),
        ),
        migrations.CreateModel(
            name='StoreTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('status', models.CharField(choices=[('NeedBuy', 'need_buy'), ('WasBuy', 'was_buy')], default='NeedBuy', max_length=32)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingridient')),
            ],
        ),
    ]
