name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
        #SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          source venv/bin/activate
          cd Django-Restaurant-Purchases
          git pull ${{secrets.REPO_NAME}}
          python3 manage.py makemigrations
          python3 manage.py migrate
          pkill gunicorn
          gunicorn restaurant_purchases.wsgi:application --bind 68.183.201.244:8000 --daemon