name: Second ServerDeploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST2 }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
        #SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
        #KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/mywebsite"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
        #SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_HOST=134.122.43.197
          source venv/bin/activate
          git clone ${{secrets.REPO_NAME}}
          cd Django-Restaurant-Purchases
          docker-compose down
          pkill gunicorn
          docker-compose up
          #python3 manage.py makemigrations
          #python3 manage.py migrate
          #pkill gunicorn
          #gunicorn restaurant_purchases.wsgi:application --bind 134.122.43.197:8000 --daemon