name: Second Server Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    """- name: print secrets
      run: |
          echo $CERT_PEM >> /root/Django-Restaurant-Purchases/cert.pem
          echo $PRIVATE_KEY >> /root/Django-Restaurant-Purchases/private.key
          cat /root/Django-Restaurant-Purchases/cert.pem
      shell: bash
      env:
        CERT_PEM : ${{secrets.cert.pem}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: DEV_ENV_FILE
       path: src/.env"""

    - uses: actions/checkout@v1
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
        #SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_HOST=134.122.43.197
          cd Django-Restaurant-Purchases
          git pull ${{secrets.REPO_NAME}}
          echo `"${{ secrets.CERT_PEM }}"`
          echo "${{ secrets.CERT_PEM }}" > cert.pem
          echo "${{ secrets.PRIVATE_KEY }}" > private.key
          docker-compose down
          pkill gunicorn
          docker-compose build
          docker-compose up
          #python3 manage.py makemigrations
          #python3 manage.py migrate
          #pkill gunicorn
          #gunicorn restaurant_purchases.wsgi:application --bind 134.122.43.197:8000 --daemon